[book]
title = "Fowl Engine User Guide"
authors = ["Fowl Engine Team"]
description = "A comprehensive guide for players in the Fowl Engine Dynamic Campaign System for DCS"
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/yourusername/bfnext"

