[package]
name = "bfcore"
version = "0.1.0"
edition = "2021"

[dependencies]
dcso3 = { version = "0.1", path = "../dcso3" }
smallvec = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
chrono = { workspace = true }
